module.exports = {
     findPaged: (page) => {
          const offsetValue = (page - 1) * 50;
          return{sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date, '%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id order by a.ad_date desc limit 50 offset ?;`, values: [offsetValue]};
     },
     findSearched: (searched) => {
          const {location, category,search, page,option} = searched;
          const offsetValue = searched.page ? (searched.page - 1) * 50 : 0; 
          if(location == "Rwanda" && category == "All"){
               if(option === "all"){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where p.plan_id like 'plan_001' order by a.ad_date desc limit 100 offset ?; `, values: [offsetValue] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where p.plan_id like 'plan_001' and a.ad_name like concat('%',?,'%') order by a.ad_date desc;`, values: [search]}
                    }
               }else if(option === 'websites'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where a.ad_website is not null order by a.ad_date desc;`, }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where a.ad_website is not null and a.ad_name like concat('%',?,'%')  order by a.ad_date desc;`, values: [search]}
                    }
               }else if(option === 'vendors'){
                    if(!search || search === null || search === ""){
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id group by u.user_id;` }
                    }else{
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id  where u.full_name like concat('%',?,'%') or u.username like concat('%',?,'%') or u.user_email like concat('%',?,'%') or u.user_phone like concat('%',?,'%') group by u.user_id;`, values: [search, search,search,search] }
                    }
               }else if(option === 'deals'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where a.ad_discount > 1 order by a.ad_date  desc;` }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where a.ad_discount > 1 and a.ad_name like concat('%',?,'%') order by a.ad_date  desc;`, values: [search] }
                    }
               }else if(option === 'featured'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%' order by a.ad_date  desc;` }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where a.ad_name like concat('%',?,'%') and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;`, values: [search] }
                    }
               }
          }else if (location === "Rwanda" && category !== "All"){
               if(option === "all"){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where p.plan_id like 'plan_001' and category.category_id = ? order by a.ad_date desc; `, values: [category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where p.plan_id like 'plan_001' and category.category_id = ? and a.ad_name like concat('%',?,'%') order by a.ad_date desc;`, values: [category,search]}
                    }
               }else if(option === 'websites'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where  category.category_id = ? and a.ad_website is not null order by a.ad_date desc;`, values:[category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where  category.category_id = ? and a.ad_website is not null and a.ad_name like concat('%',?,'%')  order by a.ad_date desc;`, values: [category,search]}
                    }
               }else if(option === 'vendors'){
                    if(!search || search === null || search === ""){
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id group by u.user_id limit 50;` }
                    }else{
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id  where u.full_name like concat('%',?,'%') or u.username like concat('%',?,'%') or u.user_email like concat('%',?,'%') or u.user_phone like concat('%',?,'%') group by u.user_id limit 50;`, values: [search, search,search,search] }
                    }
               }else if(option === 'deals'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where  category.category_id = ? and a.ad_discount > 1 order by a.ad_date  desc limit 50;`, values: [category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where  category.category_id = ? and a.ad_discount > 1 and a.ad_name like concat('%',?,'%') order by a.ad_date  desc;`, values: [category,search] }
                    }
               }else if(option === 'featured'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where  category.category_id = ? and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;`,values: [category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where category.category_id = ? and a.ad_name like concat('%',?,'%') and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;`, values: [category,search] }
                    }
               }
          }else if (category === "All" && location !== "Rwanda"){
               if(option === "all"){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and p.plan_id like 'plan_001' order by a.ad_date desc;`, values: [location] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and p.plan_id like 'plan_001' and a.ad_name like concat('%',?,'%') order by a.ad_date desc;`, values: [location,search, offsetValue]}
                    }
               }else if(option === 'websites'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and a.ad_website is not null order by a.ad_date desc;`,values:[location] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and a.ad_website is not null and a.ad_name like concat('%',?,'%')  order by a.ad_date desc;`, values: [location,search]}
                    }
               }else if(option === 'vendors'){
                    if(!search || search === null || search === ""){
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') group by u.user_id limit 50;`,values:[location] }
                    }else{
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id  where json_extract(u.user_location, '$.location') like concat('%',?,'%') and (u.full_name like concat('%',?,'%') or u.username like concat('%',?,'%') or u.user_email like concat('%',?,'%') or u.user_phone like concat('%',?,'%')) group by u.user_id limit 50;`, values: [location,search, search,search,search] }
                    }
               }else if(option === 'deals'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and a.ad_discount > 1 order by a.ad_date  desc;`,values:[location] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and a.ad_discount > 1 and a.ad_name like concat('%',?,'%') order by a.ad_date  desc;`, values: [location,search] }
                    }
               }else if(option === 'featured'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;` ,values:[location] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and a.ad_name like concat('%',?,'%') and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;`, values: [location,search] }
                    }
               }
          }else {
               if(option === "all"){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and p.plan_id like 'plan_001' order by a.ad_date desc; `, values: [location,category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and p.plan_id like 'plan_001' and a.ad_name like concat('%',?,'%') order by a.ad_date desc;`, values: [location,category,search, offsetValue]}
                    }
               }else if(option === 'websites'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and a.ad_website is not null order by a.ad_date desc;`,values:[location, category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and a.ad_website is not null and a.ad_name like concat('%',?,'%')  order by a.ad_date desc;`, values: [location,category,search]}
                    }
               }else if(option === 'vendors'){
                    if(!search || search === null || search === ""){
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id group by u.user_id;` }
                    }else{
                         return {sql: `select u.user_id, u.username, u.full_name,u.profile_image, u.user_phone, u.user_email, p.plan_name, sum(a.ad_views) as total_views, count(a.ad_id) as total_ads from users u inner join payment_plan p on u.ad_plan_id = p.plan_id inner join adverts a on u.user_id = a.ad_user_id  where u.full_name like concat('%',?,'%') or u.username like concat('%',?,'%') or u.user_email like concat('%',?,'%') or u.user_phone like concat('%',?,'%') group by u.user_id;`, values: [search, search,search,search] }
                    }
               }else if(option === 'deals'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and a.ad_discount > 1 order by a.ad_date  desc;`, values:[location, category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and a.ad_discount > 1 and a.ad_name like concat('%',?,'%') order by a.ad_date  desc;`, values: [location,category,search] }
                    }
               }else if(option === 'featured'){
                    if(!search || search === null || search === ""){
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;`, values:[location, category] }
                    }else{
                         return {sql: `select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where json_extract(u.user_location, '$.location') like concat('%',?,'%') and category.category_id = ? and a.ad_name like concat('%',?,'%') and (p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%featured%') order by a.ad_date  desc;`, values: [location, category, search] }
                    }
               }
          }
     },
     testFind: 'select * from adverts',
     countAll: "select count(*) as totalAdverts from adverts where ad_plan_id = 'plan_001';",
     selectAll:"select * from adverts;",
     selectApprovedAds: "select a.ad_id, a.ad_name,a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_user_id, a.ad_price, a.sub_category_id, a.status, a.ad_discount, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_plan_id, a.ad_website, a.ad_rank from adverts a left join commission_ads c on a.ad_id = c.ad_id where a.status = 'Approved' and c.ad_id is null order by a.ad_date desc;",
     selectPendingAds : "select a.ad_id, a.ad_name,a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_user_id, a.ad_price, a.sub_category_id, a.status, a.ad_discount, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_plan_id, a.ad_website, a.ad_rank from adverts a left join commission_ads c on a.ad_id = c.ad_id where a.status = 'pending' and c.ad_id is null order by a.ad_date desc;",
     selectRejectedAds: "select a.ad_id, a.ad_name,a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_user_id, a.ad_price, a.sub_category_id, a.status, a.ad_discount, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_plan_id, a.ad_website, a.ad_rank from adverts a where a.status = 'rejected' order by a.ad_date desc;",
     selectApprovedCommissionAds: "select a.ad_id, a.ad_name,a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_user_id, a.ad_price, a.sub_category_id, a.status, a.ad_discount, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_plan_id, a.ad_website, a.ad_rank from adverts a inner join commission_ads c on a.ad_id = c.ad_id where a.status = 'Approved' order by a.ad_date desc",
     selectPendingCommissionAds: "select a.ad_id, a.ad_name,a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_user_id, a.ad_price, a.sub_category_id, a.status, a.ad_discount, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_plan_id, a.ad_website, a.ad_rank from adverts a inner join commission_ads c on a.ad_id = c.ad_id where a.status = 'pending' order by a.ad_date desc;",
     selectAllApproved: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' group by a.ad_id order by a.ad_date desc;",
     selectListingAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and p.plan_name in ('VIP','VVIP','Basic','basic','premium') group by a.ad_id order by a.ad_date desc limit ? offset ?;",
     selectFreeAds: "select a.ad_id, a.ad_name, a.ad_image, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_discount, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id left join commission_ads ca on a.ad_id = ca.ad_id where u.active is true and a.status = 'Approved' and p.plan_name in ('free','freemium', 'Free') and category.category_id <> 'bed1566b-5901-4af9-ae80-708c293aa925' and category.category_id <> 'b6b8d2d5-476d-48a3-beb0-93f01ecc4ef7' and ca.ad_id is null group by a.ad_id order by a.ad_date desc limit ? offset ?;",
     selectUrgentAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and p.plan_name = 'urgent' group by a.ad_id order by a.ad_date desc limit ? offset ?;",
     selectSponsoredAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and p.plan_name in ('sponsored') group by a.ad_id order by a.ad_date desc limit ? offset ?;",
     selectClientApprovedCommissionAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views, ca.commission from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id inner join commission_ads ca on a.ad_id = ca.ad_id where u.active is true and a.status = 'Approved' group by a.ad_id order by a.ad_date desc, ca.commission desc limit ? offset ?;",
     selectApprovedAdsByCategory: "select a.ad_id, a.ad_name, a.ad_image, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_discount, a.description, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.verified, a.ad_website as website, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join commission_ads ca on a.ad_id = ca.ad_id where u.active is true and a.status = 'Approved' and category.category_id in (?) and ca.ad_id is null ORDER BY ad_date desc, a.ad_price desc limit ? offset ?;",
     selectApprovedCommissionAdsByCategory: "select a.ad_id, a.ad_name, a.ad_image, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.contact, a.ad_discount, a.description, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id inner join commission_ads ca on a.ad_id = ca.ad_id where u.active is true and a.status = 'Approved' and category.category_id in (?) group by a.ad_id order by a.ad_date ASC limit ? offset ?;",
     countAllAds: "select count(*) as total from adverts;",
     countNewAds: "select count(a.ad_id) as total from adverts a where date_format(a.ad_date, '%Y-%m-%d') = ?;",
     countFreeAds: "select count(*) as total from adverts a inner join payment_plan p on a.ad_plan_id = p.plan_id inner join sub_category s on a.sub_category_id = s.sub_id inner join category c on s.parent_id = c.category_id left join commission_ads ca on a.ad_id = ca.ad_id where p.plan_name in ('free','freemium', 'Free') and c.category_id <> 'bed1566b-5901-4af9-ae80-708c293aa925' and ca.ad_id is null;",
     countListingAds: "select count(*) as total from adverts a inner join payment_plan p on a.ad_plan_id = p.plan_id where p.plan_name in ('VIP','VVIP','Basic','basic','premium');",
     countUrgentAds: "select count(*) as total from adverts a inner join payment_plan p on a.ad_plan_id = p.plan_id where p.plan_name in ('urgent');",
     countSponsoredAds: "select count(*) as total from adverts a inner join payment_plan p on a.ad_plan_id = p.plan_id where p.plan_name in ('sponsored');",
     countApprovedShopAds: "select count(*) as total from adverts where ad_user_id = ? and status = 'Approved';",
     selectApprovedShopAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and u.user_id = ? and a.ad_id <> ? group by a.ad_id order by a.ad_date desc limit ? offset ?;",
     selectApprovedCategoryAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and category.category_id = ? and a.ad_id <> ? group by a.ad_id order by a.ad_date desc,a.ad_rank desc limit ? offset ?;",
     selectApprovedSubCategoryAds: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and c.sub_id = ? group by a.ad_id order by a.ad_date desc, a.ad_rank desc limit ? offset ?;",
     selectApprovedByLocation: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and json_unquote(json_extract(u.user_location, '$.location')) = ?  group by a.ad_id order by a.ad_date desc limit ? offset ?;",
     countApprovedByLocation: "select count(a.ad_id) as total from adverts a inner join users u on a.ad_user_id = u.user_id  where u.active is true and a.status = 'Approved' and json_unquote(json_extract(u.user_location, '$.location')) = ?  group by json_unquote(json_extract(u.user_location, '$.location'));",
     findAll: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on category.parent_id = category.category_id where u.active is true and a.status = 'Approved' order by a.ad_date desc limit 50 ;",
     getCategory: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_id,category.category_name from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where category.category_id = ? and u.active = 1 and a.status = 'Approved' order by CAST(a.ad_date AS DATETIME) DESC limit 100;",
     // findAllPaged: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where p.plan_name like '%freemium%' order by a.ad_date desc limit 50 offset ?; ",
     findAllPaged: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and p.plan_id like 'plan_001' and a.status = 'Approved' order by a.ad_date desc limit 50 offset ?; ",
     findBoosted: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and a.status = 'Approved' and p.plan_name like '%premium%' or p.plan_name like '%urgent%' or p.plan_name like '%basic%' or p.plan_name like 'enterprise' order by a.ad_date  desc limit ?;",
     findDiscounts: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and a.status = 'Approved' and a.ad_discount > 1 or a.ad_plan_id = 'plan_003'  order by a.ad_date  desc limit ?;",
     findWebsites: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, a.ad_discount, a.ad_website, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_name, category.category_id from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and a.status = 'Approved' and a.ad_website is not null and a.ad_website <> 'null' and a.ad_website <> '' and a.ad_plan_id = 'plan_005' order by a.ad_date desc limit ?;",
     // searchAdverts: "select (char_length(a.ad_name) - char_length(replace(a.ad_name, ?, ''))) / char_length(?) * 100 as inclusion_percentage, a.ad_id, a.ad_name, a.ad_image, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_name, p.plan_name, u.full_name, u.user_location,u.user_phone, u.user_email, category.category_id,category.category_name from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where a.ad_name like concat('%',?,'%') order by inclusion_percentage desc;",
     searchAdverts: "select (char_length(a.ad_name) - char_length(replace(a.ad_name, ?, ''))) / char_length(?) * 100 as inclusion_percentage, a.ad_id, a.ad_name, a.ad_image, a.ad_type, a.ad_price, a.ad_date, a.status, a.contact, a.ad_views, c.sub_name, p.plan_name, u.full_name, u.user_location,u.user_phone, u.user_email, u.verified, category.category_id,category.category_name from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is verified and a.status = 'Approved' and  a.ad_name like concat('%',?,'%') order by inclusion_percentage desc;",
     searchAdvertsSub: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified,category.category_id, category.category_name from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and c.sub_id in (select sub_id from sub_category where sub_name like concat('%', ?, '%')) and a.status = 'Approved';",
     searchAdvertsCat: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_id,category.category_name from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and category.category_id in (select category_id from category where category_name like concat('%',?,'%')) and a.status = 'Approved';",
     searchAdvertsUser: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_id,category.category_name from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id where u.active is true and u.user_id in (select user_id from users where full_name like concat('%',?,'%') or username like concat('%',?,'%'));",
     getSimilarCategory: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_id,category.category_name, count(w.v_id) from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id inner join web_views w on a.ad_id = w.v_id where u.active is true and category.category_id = ? and a.ad_id <> ? and a.status = 'Approved' group by w.v_id;",
     getSubCategory: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified,category.category_id, category.category_name, count(w.v_id) from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id inner join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and c.sub_id = ? group by w.v_id;",
     getSimilarSubCategory: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified,category.category_id, category.category_name, count(w.v_id) as ad_visits from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id where u.active is true and a.status = 'Approved' and c.sub_id = ? and a.ad_id <> ? group by a.ad_id;",
     getUserAdverts: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d') as ad_date, a.status, a.contact, a.ad_views, c.sub_id, c.sub_name, p.plan_name, u.full_name, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, category.category_name, category.category_id, count(w.v_id) as ad_visits, ca.commission from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on  a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id left join commission_ads ca on ca.ad_id = a.ad_id where a.status = 'Approved' and u.user_id = ? group by a.ad_id;",
     // findAll: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.ad_date, c.sub_id, p.plan_name, u.full_name, u.user_location, u.profile_image from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id;",
     add: "insert into adverts (ad_id, ad_name, description, ad_image, ad_images, ad_type, ad_user_id, ad_price, sub_category_id,ad_date, contact) values (?,?,?,?,?,?,?,?,?,?,?)",
     search: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, a.contact, a.ad_views, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, c.sub_id, c.sub_name, p.plan_name, u.user_id, u.full_name, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, date_format(u.reg_date, '%Y-%m-%d') as reg_date, category.category_id, category.category_name, count(w.v_id) as ad_views, ca.commission  from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id inner join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id left join commission_ads ca on a.ad_id = ca.ad_id where a.ad_id = ? group by a.ad_id;",
     searchAd: "select * from adverts where ad_id = ?",
     update: "update adverts set ad_name = ?, description = ?, ad_image = ?, ad_images = ?, ad_type = ?, contact = ?, ad_price = ?, ad_discount = ?  where ad_id = ?;",
     updateAd: "update adverts set ad_name = ?, description = ?, ad_image = ?, ad_type = ?, ad_price = ?, sub_category_id = ?,  status = ?,  ad_discount = ?, contact = ?, ad_plan_id = ?, ad_website = ? where ad_id = ?;",
     // delete: "delete from adverts where ad_id = ?;",
     delete: "update adverts set status = 'rejected' where ad_id = ?;",
     addAdView: "update adverts set ad_views = ? where ad_id = ?;",
     addAdDiscount: "update adverts set ad_discount = ? where ad_id = ?;",
     selectSpecialShop: "select a.ad_id, a.ad_name, a.description, a.ad_image, a.ad_images, a.ad_type, a.ad_price, date_format(a.ad_date,'%Y-%m-%d %H:%i:%s') as ad_date, a.status, a.contact, a.ad_discount, c.sub_id, c.sub_name, p.plan_name, u.full_name,u.user_id, u.username, u.user_location, u.profile_image,u.user_phone, u.user_email, u.rating, u.verified, a.ad_website as website, category.category_name, category.category_id, count(w.v_id) as ad_views, ca.commission from adverts a inner join users u on a.ad_user_id = u.user_id inner join sub_category c on a.sub_category_id = c.sub_id left join payment_plan p on a.ad_plan_id = p.plan_id inner join category  on c.parent_id = category.category_id left join web_views w on a.ad_id = w.v_id left join commission_ads ca on a.ad_id = ca.ad_id where u.active is true and a.status = 'Approved' and c.sub_id in (?) and u.user_id in (?) group by a.ad_id order by a.ad_date desc, ca.commission desc limit ? offset ?;"

}